gridgain/gridgain

examples/pom-standalone-lgpl.xml
examples/pom-standalone.xml

@ygerzhedovich please, have a look

GG-19296: Add mleap dependency to pom.xml for examples in CE binary builds

---

modules/clients/src/test/java/org/apache/ignite/internal/client/ThinClientCustomQueryRegistryTest.java
modules/clients/src/test/java/org/apache/ignite/internal/client/suite/IgniteClientTestSuite.java
modules/core/src/main/java/org/apache/ignite/internal/processors/platform/client/ClientCustomQueryRequest.java
modules/core/src/main/java/org/apache/ignite/internal/processors/platform/client/ClientMessageParser.java
modules/core/src/main/java/org/apache/ignite/internal/processors/platform/client/CustomQueryProcessor.java
modules/core/src/main/java/org/apache/ignite/internal/processors/platform/client/ThinClientCustomQueryRegistry.java
modules/ml/src/main/java/org/apache/ignite/ml/inference/storage/model/DefaultModelStorage.java
modules/ml/src/main/java/org/apache/ignite/ml/inference/storage/model/Directory.java
modules/ml/src/main/java/org/apache/ignite/ml/inference/storage/model/File.java
modules/ml/src/main/java/org/apache/ignite/ml/inference/storage/model/FileOrDirectory.java
modules/ml/src/main/java/org/apache/ignite/ml/inference/storage/model/FileStat.java
modules/ml/src/main/java/org/apache/ignite/ml/inference/storage/model/ModelStorage.java
modules/ml/src/main/java/org/apache/ignite/ml/inference/storage/model/thinclient/FileRespose.java
modules/ml/src/main/java/org/apache/ignite/ml/inference/storage/model/thinclient/FileStatResponse.java
modules/ml/src/main/java/org/apache/ignite/ml/inference/storage/model/thinclient/FilesListResponse.java
modules/ml/src/main/java/org/apache/ignite/ml/inference/storage/model/thinclient/ModelStorateThinClientProcessor.java
modules/ml/src/main/java/org/apache/ignite/ml/inference/storage/model/thinclient/package-info.java
modules/ml/src/main/java/org/apache/ignite/ml/util/plugin/MLPluginProvider.java
modules/ml/src/test/java/org/apache/ignite/ml/inference/IgniteModelStorageUtilTest.java
modules/ml/src/test/java/org/apache/ignite/ml/inference/InferenceTestSuite.java
modules/ml/src/test/java/org/apache/ignite/ml/inference/storage/model/AbstractModelStorageTest.java
modules/ml/src/test/java/org/apache/ignite/ml/inference/storage/model/thinclient/ModelStorateThinClientProcessorTest.java

@dmitrievanthony, please, have a look

GG-19172: [ML] Extend binary protocol for working with model storage

---

modules/codegen/src/main/java/org/apache/ignite/codegen/MessageCodeGenerator.java
modules/core/src/main/java/org/apache/ignite/internal/processors/query/messages/GridQueryKillRequest.java
modules/core/src/main/java/org/apache/ignite/internal/processors/query/messages/GridQueryKillResponse.java

This fixes rolling upgrade issues.

 GG-19398:  [GG-19389] Code-generated GridQueryKillResponse and GridQueryKillRequest.

---

modules/codegen/src/main/java/org/apache/ignite/codegen/MessageCodeGenerator.java
modules/core/src/main/java/org/apache/ignite/internal/processors/query/messages/GridQueryKillRequest.java
modules/core/src/main/java/org/apache/ignite/internal/processors/query/messages/GridQueryKillResponse.java

This fixes rolling upgrade issues.

GG-19389: Code-generated GridQueryKillResponse and GridQueryKillRequest.

---

modules/ml/mleap-model-parser/pom.xml
modules/ml/spark-model-parser/pom.xml
modules/ml/tensorflow-model-parser/pom.xml
modules/ml/xgboost-model-parser/pom.xml

GG-19232: Enormous size of binary artifacts

---

modules/yardstick/src/main/java/org/apache/ignite/yardstick/IgniteAbstractBenchmark.java

Initially implemented in the IGNITE-10053 and IGNITE-9447.

GG-19435: Fixes for benchmars freezes

---

modules/web-console/frontend/package-lock.json
modules/web-console/frontend/package.json

The changes from this PR consistently appear after package installation, so included these.

GG-19664 Update package-lock.json.

---

modules/compress/README.txt
modules/compress/licenses/gg-community.txt
modules/hibernate-5.3/README.txt
modules/ml/mleap-model-parser/README.txt
modules/ml/mleap-model-parser/licenses/apache-2.0.txt
modules/ml/mleap-model-parser/licenses/gg-community.txt
modules/ml/spark-model-parser/README.txt
modules/ml/spark-model-parser/licenses/apache-2.0.txt
modules/ml/spark-model-parser/licenses/gg-community.txt
modules/ml/tensorflow-model-parser/README.txt
modules/ml/tensorflow-model-parser/licenses/apache-2.0.txt
modules/ml/tensorflow-model-parser/licenses/gg-community.txt
modules/ml/xgboost-model-parser/README.txt
modules/ml/xgboost-model-parser/licenses/apache-2.0.txt
modules/ml/xgboost-model-parser/licenses/gg-community.txt

GG-20258: Miss mandatory files in ignite-compress, ignite-direct-io, ignite-ml-*

---

modules/tensorflow/pom.xml

GG-20277: A lot of new libs in ignite-tensorflow

---

modules/web-console/frontend/app/components/web-console-sidebar/web-console-sidebar-overflow/controller.ts

No idea why this didn't break before.

GG-19606 Fix sidebar width

---

examples/src/main/java/org/apache/ignite/examples/ml/preprocessing/MaxAbsScalerExample.java
examples/src/main/java/org/apache/ignite/examples/ml/preprocessing/MinMaxScalerExample.java
examples/src/main/java/org/apache/ignite/examples/ml/preprocessing/StandardScalerExample.java

GG-20571 ML preprocessing examples print out incorrect last line

---

modules/core/src/main/java/org/apache/ignite/spi/discovery/tcp/ServerImpl.java
modules/core/src/test/java/org/apache/ignite/spi/discovery/tcp/TcpDiscoverySelfTest.java

fix ringLatencyCheck loop if there is only one server node with clients in topology

GG-21206 fix ringLatencyCheck loop

---

modules/core/src/main/java/org/apache/ignite/cache/CacheKeyConfiguration.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/ClusterCachesInfo.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/GridCacheUtils.java
modules/core/src/test/java/org/apache/ignite/internal/processors/cache/CacheAffinityKeyConfigurationMismatchTest.java
modules/core/src/test/java/org/apache/ignite/testsuites/IgniteCacheTestSuite.java

Signed-off-by: Andrey Gura <agura@apache.org>
(cherry picked from commit 1ea1505872b0dce8386ca3975a346fbfd2482dad)

GG-22140 [IGNITE-7883] Cluster can have inconsistent affinity configuration.

---

examples/pom-standalone-lgpl.xml
examples/pom-standalone.xml

GG-22333: Can not build examples for 8.7.7

---

modules/geospatial/src/test/java/org/apache/ignite/internal/processors/query/h2/H2IndexesSystemViewTest.java
modules/geospatial/src/test/java/org/apache/ignite/testsuites/GeoSpatialIndexingTestSuite.java
modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/H2TableDescriptor.java
modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/H2Utils.java
modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/IgniteH2Indexing.java
modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/database/H2IndexType.java
modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/database/H2Tree.java
modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/database/H2TreeIndex.java
modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/database/IndexInformation.java
modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/opt/GridH2PrimaryScanIndex.java
modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/opt/GridH2Table.java
modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/sys/view/SqlSystemViewIndexes.java
modules/indexing/src/test/java/org/apache/ignite/internal/processors/query/SqlSystemViewsSelfTest.java

GG-22147: SQL: Create a view with list of existing indexes

GG-22147: SQL: Create a view with list of existing indexes

---

modules/core/src/main/java/org/apache/ignite/internal/IgniteFeatures.java

GG-23450 Add IgniteFeature indicating that Web Console can collect DR events from this grid

---

modules/web-console/frontend/app/components/ui-grid/controller.js
modules/web-console/frontend/app/components/ui-grid/decorator.js

https://ggsystems.atlassian.net/browse/GG-24122

GG-24122 Fixed behaviour of group header selection

---

modules/web-console/frontend/app/primitives/dropdown/index.scss

https://ggsystems.atlassian.net/browse/GG-17923

GG-17923: Remove manual z-index from dropdown-menu

---

modules/web-console/frontend/app/components/bs-select-menu/strip.filter.ts
modules/web-console/frontend/app/components/bs-select-menu/style.scss
modules/web-console/frontend/app/components/bs-select-menu/template.pug
modules/web-console/frontend/app/components/ignite-chart-series-selector/controller.js
modules/web-console/frontend/app/components/ignite-chart-series-selector/style.scss

https://ggsystems.atlassian.net/browse/GG-17979

GG-17979: implemented colored lines in dropdown menu on charts

---

modules/web-console/frontend/app/components/ui-grid-filters/style.scss
modules/web-console/frontend/app/components/ui-grid-filters/template.pug

https://ggsystems.atlassian.net/browse/GG-17727

GG-17727: Remove blue box-shadow on sort button for filter ui-grid-headers

---

modules/web-console/web-agent/pom.xml
modules/web-console/web-agent/src/main/java/org/apache/ignite/console/agent/handlers/WebSocketRouter.java
modules/web-console/web-agent/src/main/java/org/apache/ignite/console/agent/rest/RestExecutor.java
modules/web-console/web-agent/src/main/java/org/apache/ignite/console/demo/service/DemoCachesLoadService.java
modules/web-console/web-agent/src/test/java/org/apache/ignite/console/agent/rest/RestExecutorSelfTest.java

GG-23315 Long running action in node blocks requests processing in agent.

---

modules/web-console/web-agent/src/main/java/org/apache/ignite/console/demo/service/DemoCachesLoadService.java
modules/web-console/web-console-common/src/main/java/org/apache/ignite/console/utils/Utils.java
modules/web-console/web-console-server/src/main/java/org/apache/ignite/console/services/AdminService.java
modules/web-console/web-console-server/src/main/java/org/apache/ignite/console/web/socket/AgentKey.java
modules/web-console/web-console-server/src/main/java/org/apache/ignite/console/web/socket/AgentsRepository.java
modules/web-console/web-console-server/src/main/java/org/apache/ignite/console/web/socket/AgentsService.java
modules/web-console/web-console-server/src/main/java/org/apache/ignite/console/web/socket/BrowsersService.java
modules/web-console/web-console-server/src/main/java/org/apache/ignite/console/web/socket/ClustersRepository.java
modules/web-console/web-console-server/src/main/java/org/apache/ignite/console/web/socket/TransitionService.java
modules/web-console/web-console-server/src/test/java/org/apache/ignite/console/MockConfiguration.java
modules/web-console/web-console-server/src/test/java/org/apache/ignite/console/listener/NotificationEventListenerTest.java
modules/web-console/web-console-server/src/test/java/org/apache/ignite/console/web/socket/TransitionServiceSelfTest.java

GG-23374 Implemented events collection in case of multi backends deployment.

---

modules/web-console/assembly/README.txt

GG-24696: [WC] Migration instructions of persistence folder to new Web Console release

---

modules/core/src/test/java/org/apache/ignite/internal/IgniteClientReconnectFailoverAbstractTest.java
modules/core/src/test/java/org/apache/ignite/internal/processors/cache/query/CacheScanQueryFailoverTest.java
modules/indexing/src/test/java/org/apache/ignite/internal/processors/cache/BigEntryQueryTest.java
modules/indexing/src/test/java/org/apache/ignite/internal/processors/cache/CacheQueryEvictDataLostTest.java
modules/indexing/src/test/java/org/apache/ignite/internal/processors/cache/distributed/near/IgniteCacheDistributedPartitionQueryNodeRestartsSelfTest.java
modules/indexing/src/test/java/org/apache/ignite/internal/processors/cache/index/BasicIndexTest.java
modules/indexing/src/test/java/org/apache/ignite/internal/processors/query/AbstractQueryTableLockAndConnectionPoolSelfTest.java
modules/indexing/src/test/java/org/apache/ignite/internal/processors/query/SqlSchemaSelfTest.java

(cherry picked from commit ec5bfbe672f6a35cb611df2db73d9a4a716a0802)

GG-21543 Speedup Queries 1 test suite (#574)

---

modules/gmc-agent/src/main/java/org/gridgain/action/controller/QueryActionsController.java
modules/gmc-agent/src/test/java/org/gridgain/action/controller/QueryActionsControllerTest.java

https://ggsystems.atlassian.net/browse/GG-23951

GG-23951: Return scan query response result as singleton list

---

modules/indexing/src/test/java/org/apache/ignite/internal/processors/cache/CacheGroupMetricsWithIndexTest.java

Add counter left partition for index rebuild in CacheGroupMetricsMXBean

GG-24653 [8.8-next]-[GG-24337] Extend test coverage [GG-18936]-[IGNITE-11512]

---

modules/indexing/src/test/java/org/apache/ignite/internal/processors/cache/CacheGroupMetricsMBeanWithIndexTest.java

Add counter left partition for index rebuild in CacheGroupMetricsMXBean

GG-24654 [8.7-next]-[GG-24337] Extend test coverage [GG-18936]-[IGNITE-11512]

---

modules/management-console-agent/src/main/java/org/apache/ignite/agent/dto/NodeConfiguration.java
modules/management-console-agent/src/main/java/org/apache/ignite/agent/dto/action/AuthenticateCredentials.java
modules/management-console-agent/src/main/java/org/apache/ignite/agent/dto/action/InvalidRequest.java
modules/management-console-agent/src/main/java/org/apache/ignite/agent/dto/action/Request.java
modules/management-console-agent/src/main/java/org/apache/ignite/agent/dto/action/Response.java
modules/management-console-agent/src/main/java/org/apache/ignite/agent/dto/action/ResponseError.java
modules/management-console-agent/src/main/java/org/apache/ignite/agent/dto/action/query/NextPageQueryArgument.java
modules/management-console-agent/src/main/java/org/apache/ignite/agent/dto/action/query/QueryArgument.java
modules/management-console-agent/src/main/java/org/apache/ignite/agent/dto/action/query/QueryField.java
modules/management-console-agent/src/main/java/org/apache/ignite/agent/dto/action/query/QueryResult.java
modules/management-console-agent/src/main/java/org/apache/ignite/agent/dto/action/query/ScanQueryArgument.java
modules/management-console-agent/src/main/java/org/apache/ignite/agent/dto/cache/CacheInfo.java
modules/management-console-agent/src/main/java/org/apache/ignite/agent/dto/cache/CacheSqlIndexMetadata.java
modules/management-console-agent/src/main/java/org/apache/ignite/agent/dto/cache/CacheSqlMetadata.java
modules/management-console-agent/src/main/java/org/apache/ignite/agent/dto/cluster/BaselineInfo.java
modules/management-console-agent/src/main/java/org/apache/ignite/agent/dto/cluster/ClusterInfo.java
modules/management-console-agent/src/main/java/org/apache/ignite/agent/dto/topology/Node.java
modules/management-console-agent/src/main/java/org/apache/ignite/agent/dto/tracing/Annotation.java
modules/management-console-agent/src/main/java/org/apache/ignite/agent/dto/tracing/Span.java
modules/management-console-agent/src/main/java/org/apache/ignite/agent/processor/ManagementConsoleMessagesProcessor.java
modules/management-console-agent/src/main/java/org/apache/ignite/agent/ws/RetryableSender.java
modules/management-console-agent/src/test/java/org/apache/ignite/agent/processor/ManagementConsoleMessagesProcessorTest.java
modules/management-console-agent/src/test/java/org/apache/ignite/agent/ws/RetryableSenderTest.java

(cherry picked from commit c7bc473e381d19af0e336412aa69593a34389ee1)

GG-25821 Fix RetryableSender send method. (#721)

---

modules/management-console-agent/src/main/java/org/apache/ignite/agent/ManagementConsoleProcessor.java
modules/management-console-agent/src/test/java/org/apache/ignite/agent/AgentCommonAbstractTest.java
modules/management-console-agent/src/test/java/org/apache/ignite/agent/ManagementConsoleProcessorTest.java
modules/management-console-agent/src/test/java/org/apache/ignite/agent/config/TestChannelInterceptor.java
modules/management-console-agent/src/test/java/org/apache/ignite/agent/processor/AbstractServiceTest.java
modules/management-console-agent/src/test/java/org/apache/ignite/agent/processor/ManagementConsoleSpanMessagesProcessorTest.java
modules/management-console-agent/src/test/java/org/apache/ignite/agent/testsuites/AgentTestSuite.java

(cherry picked from commit 942305ee04a08cb1f6e809b4baf2cb6f1c6452ee)

GG-25930: GG-25913 Print warring message if tracing feature is not enabled. (#735)

---

modules/management-console-agent/src/main/java/org/apache/ignite/agent/utils/AgentUtils.java
modules/management-console-agent/src/test/java/org/apache/ignite/agent/testsuites/AgentTestSuite.java
modules/management-console-agent/src/test/java/org/apache/ignite/agent/utils/AgentUtilsTest.java

(cherry picked from commit 508241b3e7a8c29b91b62dfc5bce8a4753baa4f3)

GG-26046: GG-25993 Fix issue with trailing slashed in monitoring url. (#744)

---

modules/management-console-agent/src/main/java/org/apache/ignite/agent/dto/metric/MetricResponse.java
modules/management-console-agent/src/test/java/org/apache/ignite/agent/processor/export/MetricsExporterTest.java

(cherry picked from commit 51f6905ea27b94b1f63dc1a9d698305887ebe959)

GG-26276: GG-26275 Add new constructor for MetricResponse (#761)

---

modules/web-console/frontend/app/components/ignite-chart/controller.spec.ts
modules/web-console/frontend/app/components/ignite-chart/controller.ts
modules/web-console/frontend/app/components/ignite-chart/template.tpl.pug

https://ggsystems.atlassian.net/browse/GG-26106

GG-26106 [WC] Null in time of chart initialization

---

modules/management-console-agent/src/main/java/org/apache/ignite/agent/dto/topology/Node.java
modules/management-console-agent/src/test/java/org/apache/ignite/agent/dto/topology/TopologySnapshotTest.java

(cherry picked from commit 4322c4f6d901641843fd0610767d52794951d3ae)

GG-26589: GG-26416 Add node order field in topology snapshot. (#792)

---

modules/platforms/dotnet/Apache.Ignite.Core.Tests/Binary/BinaryBuilderSelfTest.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Examples/Example.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Examples/PathUtil.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/TestRunner.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Common/TaskRunner.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Unmanaged/Jni/AppDomains.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Unmanaged/UnmanagedThread.cs
modules/platforms/dotnet/build.ps1
modules/platforms/dotnet/release/verify-nuget.ps1

* Fix P/Invoke in UnmanagedThread
* Fix GetDefaultAppDomain
* Fix build.ps1 to work on Linux under PowerShell Core
This enables full development cycle on Linux with Mono, including NuGet package creation

GG-26775 .NET: Fix Mono issues

---

modules/management-console-agent/src/main/java/org/apache/ignite/agent/dto/cache/CacheInfo.java
modules/management-console-agent/src/main/java/org/apache/ignite/agent/dto/cache/CacheSqlMetadata.java
modules/management-console-agent/src/main/java/org/apache/ignite/agent/processor/CacheChangesProcessor.java
modules/management-console-agent/src/test/java/org/apache/ignite/agent/fixtures/Country.java
modules/management-console-agent/src/test/java/org/apache/ignite/agent/fixtures/CountryWithAnnotations.java
modules/management-console-agent/src/test/java/org/apache/ignite/agent/processor/CacheChangesProcessorTest.java

(cherry picked from commit 7a473307c94135bd93eece6e98bb04b9dd0b101c)

GG-26450: GG-26127 Fix GMC agent sql metadata export. (#754)

---

modules/web-console/e2e/docker-compose.yml

* Added CPU limit for backend service

GG-26849: Limit cpu usage for Web Console E2E Tests.

---

modules/management-console-agent/src/main/java/org/apache/ignite/agent/action/controller/QueryActionsController.java
modules/management-console-agent/src/main/java/org/apache/ignite/agent/dto/action/query/RunningQuery.java
modules/management-console-agent/src/test/java/org/apache/ignite/agent/action/controller/AbstractActionControllerTest.java
modules/management-console-agent/src/test/java/org/apache/ignite/agent/action/controller/AbstractActionControllerWithAuthenticationTest.java
modules/management-console-agent/src/test/java/org/apache/ignite/agent/action/controller/ActionControllerBaseTest.java
modules/management-console-agent/src/test/java/org/apache/ignite/agent/action/controller/ActionControllerWithAuthenticationBaseTest.java
modules/management-console-agent/src/test/java/org/apache/ignite/agent/action/controller/BaselineActionsControllerTest.java
modules/management-console-agent/src/test/java/org/apache/ignite/agent/action/controller/ClusterActionsControllerTest.java
modules/management-console-agent/src/test/java/org/apache/ignite/agent/action/controller/QueryActionsControllerTest.java
modules/management-console-agent/src/test/java/org/apache/ignite/agent/action/controller/QueryActionsControllerWithParametersTest.java
modules/management-console-agent/src/test/java/org/apache/ignite/agent/action/controller/SecurityActionsControllerTest.java
modules/management-console-agent/src/test/java/org/apache/ignite/agent/processor/action/DistributedActionProcessorTest.java

(cherry picked from commit cffa8a57c576c91dacae7d549276af0537f53458)

GG-27108: GG-24031 Add running queries action. (#831)

---

modules/platforms/dotnet/build.ps1

Fix .NET Core publish directory copy

GG-27256 .NET: Fix file copy logic in build script

---

modules/clients/src/test/java/org/apache/ignite/internal/processors/rest/JettyRestProcessorAbstractSelfTest.java
modules/core/src/main/java/org/apache/ignite/internal/IgniteFeatures.java
modules/rest-http/src/main/java/org/apache/ignite/internal/processors/rest/protocols/http/jetty/GridJettyObjectMapper.java
modules/rest-http/src/main/java/org/apache/ignite/internal/visor/cache/VisorCacheGetValueTask.java
modules/rest-http/src/main/java/org/apache/ignite/internal/visor/cache/VisorCacheGetValueTaskArg.java
modules/rest-http/src/main/java/org/apache/ignite/internal/visor/cache/VisorCacheKeyObject.java
modules/rest-http/src/main/java/org/apache/ignite/internal/visor/cache/VisorDataType.java

(cherry picked from commit a5e8a8313375a861ad7ec67fab3250b1b249cf6f)

GG-27464 GG-27064 Task to get value in cache with specified key. (#869)

---

modules/core/src/main/java/org/apache/ignite/events/BaselineChangedEvent.java
modules/core/src/main/java/org/apache/ignite/events/BaselineConfigurationChangedEvent.java
modules/core/src/main/java/org/apache/ignite/events/EventType.java
modules/core/src/main/java/org/apache/ignite/internal/cluster/DistributedBaselineConfiguration.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cache/GridCachePartitionExchangeManager.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cluster/DiscoveryDataClusterState.java
modules/core/src/main/java/org/apache/ignite/internal/processors/cluster/GridClusterStateProcessor.java
modules/core/src/main/java/org/apache/ignite/internal/processors/configuration/distributed/DistributedProperty.java
modules/core/src/main/java/org/apache/ignite/internal/processors/configuration/distributed/SimpleDistributedProperty.java
modules/core/src/test/java/org/apache/ignite/events/BaselineEventsLocalTest.java
modules/core/src/test/java/org/apache/ignite/events/BaselineEventsRemoteTest.java
modules/core/src/test/java/org/apache/ignite/events/BaselineEventsTest.java
modules/core/src/test/java/org/apache/ignite/testsuites/IgniteBasicTestSuite.java

(cherry picked from commit 8d62694afe4295feec64000bf7d53b7c8ea1614b)

GG-21449 New baseline event types added.

---

modules/management-console-agent/src/main/java/org/apache/ignite/agent/processor/ClusterInfoProcessor.java
modules/management-console-agent/src/test/java/org/apache/ignite/agent/processor/ClusterInfoProcessorTest.java

(cherry picked from commit 6741705e1f719b985f1f1b68269e39bf23589e30)

[GG-27666] GG-27607 Remove baseline executor service on an appropriate baseline events. (#929)

---

modules/management-console-agent/src/main/java/org/apache/ignite/agent/ManagementConsoleProcessor.java

(cherry picked from commit 84a6eb31c955f73e6472e989b980a4913c3bd7e6)

[GG-27659] GG-27658 Fix error when SpanExporter created twice (#931)

---

modules/management-console-agent/src/main/java/org/apache/ignite/agent/dto/cache/CacheInfo.java
modules/management-console-agent/src/main/java/org/apache/ignite/agent/processor/CacheChangesProcessor.java
modules/management-console-agent/src/test/java/org/apache/ignite/agent/processor/CacheChangesProcessorTest.java

(cherry picked from commit a4e16b8f5ec76acbcb072a86b250f066ac3a9e67)

GG-27976: Fix fields naming in DTO. (#977)

---

modules/management-console-agent/src/main/java/org/apache/ignite/agent/processor/export/SpanExporter.java
modules/management-console-agent/src/test/java/org/apache/ignite/agent/config/TestChannelInterceptor.java

(cherry picked from commit 6d0e9eabec5a6f77aadbe2e3e8821730b9a5b706)

GG-28074: Fix flaky tests. (#992)

---

modules/core/src/main/java/org/apache/ignite/internal/processors/platform/cache/PlatformCache.java
modules/core/src/main/java/org/apache/ignite/internal/processors/platform/cluster/PlatformClusterGroup.java
modules/platforms/dotnet/Apache.Ignite.AspNet.Tests/ExpiryCacheHolderTest.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests.DotNetCore/Apache.Ignite.Core.Tests.DotNetCore.csproj
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Cache/CacheMetricsTest.cs
modules/platforms/dotnet/Apache.Ignite.Core.Tests/Cache/CacheTestAsyncWrapper.cs
modules/platforms/dotnet/Apache.Ignite.Core/Cache/ICache.cs
modules/platforms/dotnet/Apache.Ignite.Core/Cluster/IClusterGroup.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Binary/BinaryUtils.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Cache/CacheImpl.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Cache/CacheOp.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Cluster/ClusterGroupImpl.cs
modules/platforms/dotnet/Apache.Ignite.Core/Impl/Ignite.cs

GG-27657 .NET: Enable/disable cache statistics
* `ICache.EnableStatistics`
* `ICluster.EnableStatistics`
GG-28251 .NET: Clear cache statistics
* `ICache.ClearStatistics`
* `ICluster.ClearStatistics`

GG-27657 .NET: Add ClearStatistics and EnableStatistics APIs

---

modules/core/src/main/java/org/apache/ignite/internal/processors/cache/CacheGroupMetricsImpl.java
modules/core/src/main/java/org/apache/ignite/internal/processors/query/GridQueryProcessor.java
modules/core/src/main/java/org/apache/ignite/internal/processors/query/schema/SchemaIndexCacheVisitorImpl.java
modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/IgniteH2Indexing.java
modules/indexing/src/test/java/org/apache/ignite/internal/processors/cache/CacheGroupMetricsWithIndexTest.java

(cherry picked from commit d84c5189d5f471078c557e75a2b15329c21455be)

GG-27188 JMX metric indexbuildcountpartitionsleft show values below zero

---

modules/core/src/main/java/org/apache/ignite/internal/client/thin/TcpClientTransactions.java
modules/core/src/test/java/org/apache/ignite/client/ReliabilityTest.java

(cherry picked from commit 7711fc9e37c622e358de97d8e0d8b98c23959965)

GG-28827: [IGNITE-12292] Fixed java thin transactions with id intersection

---

modules/core/src/main/java/org/apache/ignite/internal/binary/GridBinaryMarshaller.java
modules/core/src/main/java/org/apache/ignite/internal/client/thin/ClientBinaryMarshaller.java
modules/core/src/main/java/org/apache/ignite/internal/client/thin/ClientUtils.java
modules/core/src/test/java/org/apache/ignite/client/FunctionalTest.java

(cherry picked from commit 4433485d74adc109ac5f435569e18578bc9f351f)

GG-28826 [IGNITE-12468] Java thin: deserialization of collections fixed

---

modules/core/src/main/java/org/apache/ignite/internal/MarshallerContextImpl.java
modules/core/src/main/java/org/apache/ignite/internal/client/thin/TcpIgniteClient.java
modules/core/src/main/java/org/apache/ignite/marshaller/MarshallerUtils.java
modules/core/src/test/java/org/apache/ignite/client/FunctionalTest.java

(cherry picked from commit 59917f0731ea79168a3a9f03226348a6a36346b6)

GG-28825: [IGNITE-12624] Java thin: typeId generation for system types fixed

---

modules/core/src/main/java/org/apache/ignite/internal/IgniteFeatures.java

(cherry picked from commit c42fd0262d049a1facde582190b447ca87f5f76c)

GG-29432 Add DR clearStore task to Web Console.

---

modules/indexing/src/test/java/org/apache/ignite/internal/processors/query/oom/LocalQueryMemoryTrackerWithQueryParallelismSelfTest.java

GG-29726 LocalQueryMemoryTrackerWithQueryParallelismSelfTest.testQueryWithHighLimit became flaky
